### ISSUE TITLE
Basic packages for running pnlNipype, luigi-pnlpipe, etc.

### ISSUE THREAD

**Issue by tashrifbillah** [pnlbwh/luigi-pnlpipe#71]
Omitted many packaged from here:
https://github.com/pnlbwh/pnlpipe/blob/master/python_env/environment36.yml

The following seems to be our base packages.

```yml
name: pnlpipe9

channels:
  - conda-forge

dependencies:
  - python
  - ipython
  - pytest
  - plumbum
  - pandas
  - nibabel
  - nilearn
  - pyyaml
  - psutil
  - matplotlib
  - luigi
  - sqlalchemy
  - statsmodels
  - scikit-image
  - pip
  - pip:
     - git+https://github.com/dstrohl/Python_log_indenter.git
     - git+https://github.com/mhe/pynrrd.git
     - git+https://github.com/pnlbwh/conversion.git
```

@RyanZurrin, do you have any comment?
